# Generated by Django 4.2.6 on 2023-10-06 08:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("civil_id", models.CharField(blank=True, max_length=300, null=True)),
                ("department", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "enterance_time",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "permission_leaving_time",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "permission_entering_time",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "is_permit_private_1",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "is_permit_hospital_1",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_permit_official_1",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "permission_leaving_time_2",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "permission_entering_time_2",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "is_permit_private_2",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "is_permit_hospital_2",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_permit_official_2",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "permission_leaving_time_3",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "permission_entering_time_3",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "is_permit_private_3",
                    models.BooleanField(blank=True, default=True, null=True),
                ),
                (
                    "is_permit_hospital_3",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "is_permit_official_3",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "final_leaving_time",
                    models.TimeField(
                        blank=True, default=datetime.time(0, 0), null=True
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeEssentialInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "civil_id",
                    models.CharField(
                        blank=True, max_length=300, null=True, unique=True
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
