# Generated by Django 4.2.5 on 2023-09-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="leaving_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="permission_entering_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="permission_leaving_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
