# Generated by Django 4.2.5 on 2023-09-12 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0003_alter_employee_enterance_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="leaving_time",
            field=models.TimeField(blank=True, default=datetime.time(15, 0), null=True),
        ),
    ]
