# Generated by Django 4.2.5 on 2023-09-12 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0004_alter_employee_leaving_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="leaving_time",
            new_name="expected_leaving_time",
        ),
        migrations.AddField(
            model_name="employee",
            name="final_leaving_time",
            field=models.TimeField(blank=True, default=datetime.time(15, 0), null=True),
        ),
    ]
