# Generated by Django 4.2.5 on 2023-09-12 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0006_remove_employee_expected_leaving_time_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(
                blank=True, default="ELectrical Dep", max_length=300, null=True
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="permission_entering_time",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="permission_leaving_time",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
