# Generated by Django 4.2.5 on 2023-09-13 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0008_alter_sheet_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="created_date",
            field=models.DateTimeField(default=datetime.date(2023, 9, 13)),
        ),
    ]
