# Generated by Django 4.2.5 on 2023-09-13 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_sheet_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sheet",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 13, 0, 18, 38, 18348, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
