# Generated by Django 4.2.5 on 2023-09-13 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0010_alter_sheet_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 13, 11, 28, 25, 169072, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.DeleteModel(
            name="Sheet",
        ),
    ]
