# Generated by Django 4.2.5 on 2023-09-13 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0011_employee_created_date_delete_sheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 13, 11, 28, 31, 246228, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
