# Generated by Django 4.2.5 on 2023-09-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0014_alter_employee_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
