# Generated by Django 4.2.5 on 2023-09-14 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0016_alter_employee_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="permission_entering_time_2",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="permission_entering_time_3",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="permission_leaving_time_2",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="permission_leaving_time_3",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(default=datetime.date(2023, 9, 14)),
        ),
        migrations.AlterField(
            model_name="employee",
            name="enterance_time",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="final_leaving_time",
            field=models.TimeField(blank=True, default=datetime.time(0, 0), null=True),
        ),
    ]
