# Generated by Django 4.2.5 on 2023-09-17 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0017_employee_permission_entering_time_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(default=datetime.date(2023, 9, 18)),
        ),
    ]
