# Generated by Django 4.2.5 on 2023-09-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0019_employee_is_permit_hospital_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_permit_official_1",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_permit_official_2",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="is_permit_official_3",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_permit_private_1",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_permit_private_2",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_permit_private_3",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
