# Generated by Django 4.2.5 on 2023-09-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0020_employee_is_permit_official_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_permit_private_1",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
