# Generated by Django 4.2.5 on 2023-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0021_alter_employee_is_permit_private_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="is_permit_private_1",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
