# Generated by Django 4.2.5 on 2023-09-27 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0022_alter_employee_is_permit_private_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 27, 20, 56, 57, 538919, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
