# Generated by Django 4.2.5 on 2023-09-27 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0023_alter_employee_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 27, 20, 57, 15, 358474, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
