# Generated by Django 4.2.5 on 2023-09-27 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0024_alter_employee_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
