# Generated by Django 4.2.5 on 2023-10-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0025_alter_employee_created_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeEssentialInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("civil_id", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
