# Generated by Django 4.2.5 on 2023-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0026_employeeessentialinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeessentialinfo",
            name="civil_id",
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
