# Generated by Django 4.2.5 on 2023-10-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0027_alter_employeeessentialinfo_civil_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeessentialinfo",
            name="department",
            field=models.CharField(
                blank=True, default="ELectrical Dep", max_length=300, null=True
            ),
        ),
    ]
