# Generated by Django 4.2.5 on 2023-10-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0028_employeeessentialinfo_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="employeeessentialinfo",
            name="department",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
